
################################################################################
# risk: these settings are prefaced by the [risk] stanza
################################################################################
[risk]
inline = [1|0]
   * Specifies whether the summary index search command will run as part 
     of the scheduled search or as a follow-on action. This is useful 
     when the results of the scheduled search are expected to be large.
    * Defaults to 1 (true).

_name = <string>
    * The name of the summary index where Splunk will write the events.
    * Defaults to "risk".

## Using underscore prepend for risk fields because these are conveniently excluded from the summaryindex markers
## per core implementation of summaryindex alert action in $SPLUNK_HOME/etc/system/default/alert_actions.conf 

_risk_score  = <int>
    * The score to apply to risk modifiers generated by the implementation of this action
    * Defaults to 1
    
_risk_object = <string>
    * The field name to use as the risk_object
    * Field must be available in the result set passed to this action
    * Defaults to None
    
_risk_object_type = [system|user|<string>|other]
    * The type of risk_object
    * Must be one of "system", "user", arbitrary string, or "other"
    * <string> allows for type extensions
    * Defaults to None